# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 09:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=90)),
                ('last_name', models.CharField(default='', max_length=190)),
                ('last_module', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(error_messages={'unique': 'Este número ya está registrado.'}, max_length=10, validators=[django.core.validators.RegexValidator(message='Debe ingresar un número telefónico de 10 dígitos.', regex='^\\d{10}$')])),
            ],
            options={
                'verbose_name': 'encuesta',
                'verbose_name_plural': 'encuestas',
            },
        ),
    ]
